services:
  postgres:
    image: postgres:17
    container_name: presupuestos-db
    environment:
      POSTGRES_DB: presupuestos
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: alberto123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: