spring.application.name=presupuestos-api

spring.datasource.url=jdbc:postgresql://localhost:5432/presupuestos
spring.datasource.username=alberto
spring.datasource.password=alberto123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
